#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1:00:00
#SBATCH --job-name omp
#SBATCH --output=omp_%j.out


module load intel/2018.4
module load intelmpi/2018.4

rm openmp_sum.txt
./serial -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=1
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=16
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 20000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 40000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 80000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=16
./openmp -n 160000 -no -s openmp_sum.txt
./autograder -v openmp -s openmp_sum.txt
