#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1:00:00
#SBATCH --job-name omp
#SBATCH --output=omp_%j.out


module load intel/2018.4
module load intelmpi/2018.4

rm openmp_sum_small.txt
./serial -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=1
./openmp -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=2
./openmp -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=4
./openmp -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=8
./openmp -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=16
./openmp -n 2000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=2
./openmp -n 4000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=4
./openmp -n 8000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=8
./openmp -n 16000 -no -s openmp_sum_small.txt
export OMP_NUM_THREADS=16
./openmp -n 32000 -no -s openmp_sum_small.txt
./autograder -v openmp -s openmp_sum_small.txt 
